spring:
  application:
    name: procurement-app

  # db connection
  datasource:
    url: jdbc:postgresql://localhost:5432/procurement_db
    username: postgres
    password: changemeinprod!

  # JPA config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# JWT Configuration
jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 24h

